language: objective-c
osx_image: xcode7.1
script: ./test.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)

# xcode_project: contakt/contakt.xcodeproj
# xcode_scheme: contakt
# xcode_sdk: iphonesimulator9.2

# Only build PRs and pushes to master
# TODO: Change to master
branches:
  only:
    - feature/codecov
