# Well actually swift...
language: objective-c
osx_image: xcode7.2
script: ./.test.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Only build pull request's and pushes to master
branches:
  only:
    - master
